// <auto-generated />
using System;
using Kerdoivkezelo.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kerdoivkezelo.DAL.Migrations
{
    [DbContext(typeof(KerdoivKezeloDbContext))]
    [Migration("20180614093236_AddIdentity")]
    partial class AddIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Age");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Felhasznalok");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.JeloltValasz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KerdoivKitolteseFelhasznaloId");

                    b.Property<int?>("KerdoivKitolteseKerdoivId");

                    b.Property<int>("KerdoivKitoltesekId");

                    b.HasKey("Id");

                    b.HasIndex("KerdoivKitolteseFelhasznaloId", "KerdoivKitolteseKerdoivId");

                    b.ToTable("JeloltValasz");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.Kerdes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KerdoivId");

                    b.HasKey("Id");

                    b.HasIndex("KerdoivId");

                    b.ToTable("Kerdesek");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.KerdesElem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Szoveg");

                    b.HasKey("Id");

                    b.ToTable("KerdesElemek");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.KerdesOsszerendeles", b =>
                {
                    b.Property<int>("KerdesId");

                    b.Property<int>("KerdesElemId");

                    b.HasKey("KerdesId", "KerdesElemId");

                    b.HasIndex("KerdesElemId");

                    b.ToTable("KerdesOsszerendelesek");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.Kerdoiv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AtlagPontszam");

                    b.Property<int?>("ElertPontszamSzumma");

                    b.Property<int?>("IdoKorlat");

                    b.Property<int?>("KitoltesSzam");

                    b.Property<int?>("MaxPontszam");

                    b.Property<string>("Nev");

                    b.HasKey("Id");

                    b.ToTable("Kerdoivek");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.KerdoivKitoltes", b =>
                {
                    b.Property<int>("FelhasznaloId");

                    b.Property<int>("KerdoivId");

                    b.Property<int?>("AktualisKerdes");

                    b.Property<int>("Id");

                    b.Property<DateTimeOffset?>("KitoltesKezdete");

                    b.Property<DateTimeOffset?>("KitoltesVege");

                    b.Property<int?>("Pontszam");

                    b.HasKey("FelhasznaloId", "KerdoivId");

                    b.HasIndex("KerdoivId");

                    b.ToTable("KerdoivKitoltesek");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.ValaszElem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tartalom");

                    b.HasKey("Id");

                    b.ToTable("ValaszElemek");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.ValaszOsszerendeles", b =>
                {
                    b.Property<int>("ValaszElemId");

                    b.Property<int>("KerdesId");

                    b.Property<bool>("Helyes");

                    b.Property<int>("JeloltValaszId");

                    b.HasKey("ValaszElemId", "KerdesId");

                    b.HasIndex("JeloltValaszId");

                    b.HasIndex("KerdesId");

                    b.ToTable("ValaszOsszerendelesek");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.JeloltValasz", b =>
                {
                    b.HasOne("Kerdoivkezelo.DAL.Entities.KerdoivKitoltes", "KerdoivKitoltese")
                        .WithMany("JeloltValaszok")
                        .HasForeignKey("KerdoivKitolteseFelhasznaloId", "KerdoivKitolteseKerdoivId");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.Kerdes", b =>
                {
                    b.HasOne("Kerdoivkezelo.DAL.Entities.Kerdoiv")
                        .WithMany("Kerdesek")
                        .HasForeignKey("KerdoivId");
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.KerdesOsszerendeles", b =>
                {
                    b.HasOne("Kerdoivkezelo.DAL.Entities.KerdesElem", "KerdesElem")
                        .WithMany("KerdesOsszerendelesek")
                        .HasForeignKey("KerdesElemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kerdoivkezelo.DAL.Entities.Kerdes", "Kerdes")
                        .WithMany("KerdesOsszerendelesek")
                        .HasForeignKey("KerdesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.KerdoivKitoltes", b =>
                {
                    b.HasOne("Kerdoivkezelo.DAL.Entities.Felhasznalo", "Felhasznalo")
                        .WithMany("KerdoivKitoltesek")
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kerdoivkezelo.DAL.Entities.Kerdoiv", "Kerdoiv")
                        .WithMany()
                        .HasForeignKey("KerdoivId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kerdoivkezelo.DAL.Entities.ValaszOsszerendeles", b =>
                {
                    b.HasOne("Kerdoivkezelo.DAL.Entities.JeloltValasz", "JeloltValasz")
                        .WithMany("ValaszOsszerendelesek")
                        .HasForeignKey("JeloltValaszId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kerdoivkezelo.DAL.Entities.Kerdes", "Kerdes")
                        .WithMany("Valaszlehetosegek")
                        .HasForeignKey("KerdesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kerdoivkezelo.DAL.Entities.ValaszElem", "ValaszElem")
                        .WithMany("ValaszOsszerendelesek")
                        .HasForeignKey("ValaszElemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Kerdoivkezelo.DAL.Entities.Felhasznalo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Kerdoivkezelo.DAL.Entities.Felhasznalo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kerdoivkezelo.DAL.Entities.Felhasznalo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Kerdoivkezelo.DAL.Entities.Felhasznalo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
